DROP TABLE IF EXISTS song CASCADE;
DROP TABLE IF EXISTS artist CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS record CASCADE;
DROP TABLE IF EXISTS record_songs CASCADE;
DROP TABLE IF EXISTS artist_genres CASCADE;
DROP TABLE IF EXISTS artist_tags CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS record_artist CASCADE;
DROP TABLE IF EXISTS song_by CASCADE;
DROP TABLE IF EXISTS mb_artist_data CASCADE;

CREATE TABLE song (
	SID VARCHAR,
	length INTEGER,
    song_name VARCHAR,
    release_year INTEGER,
    key INTEGER,
    loudness NUMERIC,
    mode INTEGER,
    tempo NUMERIC,
    time_signature INTEGER,
    PRIMARY KEY (SID)
);

CREATE TABLE artist (
    AID VARCHAR,
    mb_id VARCHAR,
	artist_name VARCHAR,
    PRIMARY KEY (AID)
);

CREATE TABLE record (
	RID INTEGER,
	record_name VARCHAR,
	release_year INTEGER,
	record_cover_link VARCHAR,
	is_single BOOLEAN,
	PRIMARY KEY (RID)
);

CREATE TABLE record_songs (
	SID VARCHAR,
	RID INTEGER,
	PRIMARY KEY (SID, RID),
	FOREIGN KEY (SID) REFERENCES song(SID),
	FOREIGN KEY (RID) REFERENCES record(RID)
);

CREATE TABLE genre (
    GID INTEGER,
	genre_name VARCHAR,
	PRIMARY KEY (GID)
);

CREATE TABLE tag (
    TID INTEGER,
    tag_name VARCHAR,
    PRIMARY KEY (TID)
);

CREATE TABLE artist_genres (
	AID VARCHAR,
	GID INTEGER,
	PRIMARY KEY (AID, GID),
	FOREIGN KEY (AID) REFERENCES artist(AID),
	FOREIGN KEY (GID) REFERENCES genre(GID)
);

CREATE TABLE artist_tags (
	AID VARCHAR,
	TID INTEGER,
	PRIMARY KEY (AID, TID),
	FOREIGN KEY (AID) REFERENCES artist(AID),
	FOREIGN KEY (TID) REFERENCES tag(TID)
);

CREATE TABLE record_artist (
	RID INTEGER,
	AID VARCHAR,
	PRIMARY KEY (RID, AID),
	FOREIGN KEY (RID) REFERENCES record(RID),
	FOREIGN KEY (AID) REFERENCES artist(AID)
);

CREATE TABLE song_by (
	SID VARCHAR,
	AID VARCHAR,
	PRIMARY KEY (SID, AID),
	FOREIGN KEY (SID) REFERENCES song(SID),
	FOREIGN KEY (AID) REFERENCES artist(AID)
);

CREATE TABLE mb_artist_data (
    mb_global_id VARCHAR,
    mb_local_id INTEGER,
    PRIMARY KEY (mb_global_id)
);